### ISSUE TITLE
[讨论]使用.ps1脚本运行出现严重的性能问题

### ISSUE THREAD

**Issue by fatinghenji** [Franklin-Zhang0/Yolo-v8-Apex-Aim-assist#10]
仅做一个讨论，我真没弄明白是哪里出问题了，这是我使用的`.ps1`脚本：
```powershell
# 启动acconda虚拟环境
conda activate Yolo-v8-Apex-Aim-assist

# 等待用户确认
do {
    $input = Read-Host -Prompt "Press Y to continu"
} while ($input -ne "Y")

# 运行python文件
python G:\AI\Yolo-v8-Apex-Aim-assist\main.py
```
它**确实**成功的运行了，但是一旦我点击左键或者右键就会**卡卡卡卡卡**，更令我疑惑的是，如果是手动逐行使用`conda activate Yolo-v8-Apex-Aim-assist`和`python G:\AI\Yolo-v8-Apex-Aim-assist\main.py`则完全没有问题。任何人有解决的头绪吗？

#### 编辑1
我发现似乎是因为我是通过快捷方式来执行的问题，即：
1. 在桌面上创建一个快捷方式，然后右键单击快捷方式，选择“属性”，在“目标”字段中输入`powershell.exe -f "C:\Users\29099\Desktop\apexai.ps1"`。
2. 单击“快捷方式”选项卡，点击“高级”，选择“以管理员身份运行”。
3. 双击桌面上的快捷方式来运行脚本。
如果是通过直接双击`apexai.ps1`，同样不会出现性能问题。

**Comment by PTA00** [comment]
我是利用快捷.bat启动conda虚拟环境：start D:\ai\miniconda3\Scripts\activate.bat D:\ai\miniconda3\envs\aim
在游戏中会导致鼠标一卡一卡的，而游戏本身依然是300+帧，看起来像是鼠标在掉帧。
你有什么头绪吗，我已经汗流浃背了。
（未测试其他启动方式，只要开始推理鼠标就开始掉帧）

**Comment by fatinghenji** [comment]
> 我是利用快捷.bat启动conda虚拟环境：start D:\ai\miniconda3\Scripts\activate.bat D:\ai\miniconda3\envs\aim 在游戏中会导致鼠标一卡一卡的，而游戏本身依然是300+帧，看起来像是鼠标在掉帧。 你有什么头绪吗，我已经汗流浃背了。 （未测试其他启动方式，只要开始推理鼠标就开始掉帧）

是否以管理员身份运行吗

**Comment by PTA00** [comment]
https://github.com/BigdataZjk/UltralyticsYOLOv8-FPS/issues/3#issuecomment-1910012643
